// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUxyXKgqZxX4vp5_vtuHKmrmJ8wsLS3x4',
    appId: '1:956000014125:web:737c6d2406261e4552cda4',
    messagingSenderId: '956000014125',
    projectId: 'chat-app-syria2025',
    authDomain: 'chat-app-syria2025.firebaseapp.com',
    storageBucket: 'chat-app-syria2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNyXMUwX_dCCiRTZAKV86g2aTUu2MN6y0',
    appId: '1:956000014125:android:e101e69f3c00e6e352cda4',
    messagingSenderId: '956000014125',
    projectId: 'chat-app-syria2025',
    storageBucket: 'chat-app-syria2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0QXdNEaiKlawdT-Ur1OjPL7kW4rSgmmw',
    appId: '1:956000014125:ios:f3a72fa69ae695c252cda4',
    messagingSenderId: '956000014125',
    projectId: 'chat-app-syria2025',
    storageBucket: 'chat-app-syria2025.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0QXdNEaiKlawdT-Ur1OjPL7kW4rSgmmw',
    appId: '1:956000014125:ios:f3a72fa69ae695c252cda4',
    messagingSenderId: '956000014125',
    projectId: 'chat-app-syria2025',
    storageBucket: 'chat-app-syria2025.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUxyXKgqZxX4vp5_vtuHKmrmJ8wsLS3x4',
    appId: '1:956000014125:web:890cbef57a3a28e652cda4',
    messagingSenderId: '956000014125',
    projectId: 'chat-app-syria2025',
    authDomain: 'chat-app-syria2025.firebaseapp.com',
    storageBucket: 'chat-app-syria2025.firebasestorage.app',
  );
}
